### <font color='green'> Course Overview

- What to expect from the course
    
    
- How to approach the course
    - No need of:
        - taking notes
        - learn proper definitions
        - memorize syntax
    
    
- Attitude to have when programming
    - Approach to overcome issues
    
    
- Exercises
    - pseudo code is more important than technique
    
    
- Minor notes
    - Why it is entirely in english
    - Colors hierarchy

# <center> <font color='green'> Command Line, Environments, APIs, Python packages and installations

### <font color = 'green'> Terminal / prompt / Command Line
    
- <b> What is </b>
    - Comparison with UI (User Interface)
    
    
- <b> Main commands: </b>
    - pwd, cd, ls, dir, mkdir
    - rm, mv, rm -r folder
    - nano, cat, head, > .txt
    - which, whereis
    - pipe |, grep
    - history
    - sudo
    - conda
        - list, env list, activate/deactivate
    
    
- Launching python from command line
    - print('Hello')

<b> Exercise - do everything just using terminal </b>
1. Cd into your Desktop and create a file. write at least 3 lines
2. Create a folder
3. move your file into the folder
4. cd into the folder
5. create a new file out of the previous by keeping only the first 2 lines (Do not open the file!)
6. cd into your Desktop
7. remove the whole folder with the files inside
8. save the history of your commands in a file and keep it for the future

## <font color='green'> Setting up Python environment with Anaconda Distribution
- <b> Anaconda</b> 
    - It contains several tools and programming languages (i.e. Python, R, Spyder..)
    
    
- <b> Programming languages and IDEs </b>
    - IDE (Integrated Development Environment) - spyder, pycharm, jupyter notebook
    - Interpreter
    
    
- <b> What are APIs </b>
    - Modules and Packages
    
    
- <b> Python environment refers to the set of installations of packages, each with its specific version </b>
    - What are the issues and why is that useful
    
    
- <b> Launching jupyter notebook from terminal </b>
    - Installing Jupyter Extensions
    
    Useful Shortcuts:
    - tab --> autocompile
    - Shift + tab --> getting documentation
    - Ctrl + Enter --> Run commands

##### Importing python libraries

In [3]:
import sys
import os

import pandas as pd
import numpy as np

import time
from datetime import datetime

#### Installing packages
- either with conda or pip (Package Installer for Python)
- <b> NOTE </b>: you might need to use pip3!


- conda install ...
- pip install ...


- conda update conda
- pip install --upgrade pip

In [4]:
## You should have some error running this command, try to install the packages needed and rerun it

import warnings

import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.pyplot import pie, axis, show


import sklearn as sk
import tensorflow as tf

<b> Exercise: Install by yourself any packages which gave you error

In [5]:
# !pip install --upgrade pip
!pip install numpy

#### Jupyter Magic commands

In [ ]:
!ls ../.. | grep temp

In [ ]:
%timeit np.random.normal(size=10000)

In [ ]:
%matplotlib inline

In [ ]:
np.__version__

### <font color='green'> Python basics

<b> NOTE: click 'Cell' --> All Output --> Clear to cancel solutions

#### Arithmetic operations

In [ ]:
1 + 1

In [ ]:
1 * 3

In [ ]:
1 / 2

In [ ]:
2 ** 4

In [ ]:
4 % 2

In [ ]:
5 % 2

In [ ]:
(2 + 3) * (5 + 5)

In [ ]:
5//2

#### Intro to main built-in functions and special characters
Examples:
- print
- max, min
- type
- len

We'll see them more deeply later

In [ ]:
print('Hello how are you?')

In [ ]:
type(3)

In [ ]:
type([1,2,3])

In [ ]:
type('Hello')

In [ ]:
max([1,2,3])

In [ ]:
min([1,2,3])

In [ ]:
len('Hello')

In [ ]:
len([1,2])

#### Python indexing

In [180]:
'Hello'[0]

'H'

In [181]:
'Hello'[1]

'e'

In [182]:
'Hello'[-1]

'o'

### <font color = 'green'> Types of Errors
    
- <b> Multiple types </b>
    - Indentation
    - Syntax
    - ValueError
    - etc
    
    
- <b> Approach to debug </b>
    - easiest case: copy paste to google and directly find solution (stackoverflow)
    
    
- <b> conceptual errors </b>
    - obviously, if the code runs, it does not mean it is correct
    - more difficult to debug

In [ ]:
## Some Examples

2/0

In [ ]:
(1+1

In [ ]:
if 3>2:
print('Hello')

### <font color='green'> Variable Assignments
    
    
- Not related at all with math variables
    
- <b> Never name variables same as special character or built-in functions! </b>
    - nor start with a symbol or number

In [ ]:
x = 1

print(x)

In [ ]:
x = x +5

x

In [ ]:
x += 10

In [ ]:
x

In [ ]:
# Cannot start with number or special characters!

num= 5.8

round(num) 

In [ ]:
num  ## not changing the value of num, we did not assign it!

In [ ]:
# Now I am reassigning the value of num 
num= round(num)
num

In [ ]:
num += 2  # equivalent to num = num + 2
num

In [ ]:
num = 8

## Rest of the division; if it is zero, num is divisible by that
num%2

#### Alias problem

In [143]:
x = 2
y = 3

z = x + y

z

5

In [144]:
x = x + 5
x

7

Question: how much is z now?

In [145]:
z

5

and now?

In [146]:
z = x + y
z

10

In [147]:
z, x

(10, 7)

In [148]:
z = x 

z

7

In [149]:
x = 23

In [150]:
z, x

(7, 23)

In [151]:
x

23

In [154]:
# this creates a list and stores a *reference* to it:
x = [] 
# this creates another new reference to the *same list*. There's no copy.
y = x

y.append('abcd')
print(x)
print(y)

['abcd']
['abcd']


### <font color ='green' > Main Data Types
    
* Numbers
* Strings
* Booleans

#### Numbers
- int
- float

- operations (seen before)

In [156]:
type(3)

int

In [157]:
type(3.2)

float

#### Booleans
- True
- False

In [158]:
type(True)

bool

In [159]:
type(False)

bool

In [160]:
1 == 1

True

In [161]:
1==2

False

#### Strings
- Basic strings operations
- String Indexing and Slicing
- String Properties and Methods
- Print
    - Print Formatting with Strings

In [164]:
# Multiplying string

s= 'Hello '

type(s)

str

In [165]:
s*3

'Hello Hello Hello '

In [166]:
# String Concatenation
s1= 'Vorrei una '
s2= 'pasta al tartufo'

s1+s2

'Vorrei una pasta al tartufo'

In [167]:
s1

'Vorrei una '

In [168]:
s3= 'Buongiorno,'

In [170]:
s3 = s3 + ' come procede?'

s3

'Buongiorno, come procede?'

In [172]:
# Division or any other math operator not permitted; multiplication is simply replicating the string

# try:
print(s/3)

# except:
#     print('It is not possible to apply math operators to strings')

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [173]:
s= 'Vorrei una gricia'
s

'Vorrei una gricia'

In [174]:
'carbonara' in s

False

In [175]:
'gricia' in s

True

In [176]:
'ric' in s

True

In [177]:
# It considers only consecutive words
'Vorrei gricia' in s

False

In [178]:
## Print

print('Se possibile', s)

Se possibile Vorrei una gricia


Print Formatting with Strings

In [179]:
print(f'Se possibile {s}')

Se possibile Vorrei una gricia


<b> <font color='green'> Python Indexing

<b> String slicing

In [183]:
## Taking first element, it is the one at index 0
s[0]

'V'

In [184]:
## Taking i-th element
s[5]

'i'

In [185]:
## Taking last element
s[-1]

'a'

In [187]:
s[3:10]

'rei una'

In [188]:
# s did not change because we did not assign it to a new variables!
s

'Vorrei una gricia'

In [189]:
new_s= s[3:10]
new_s

'rei una'

<b> Quick Intro to Methods - we'll see more later </b> <br>
Use tab to show all the methods for a kind of class. MAIUSC + tab to check parameters for specific method

- Below some examples of string methods

In [191]:
s.startswith('v')

False

In [192]:
s.endswith('gricia')

True

In [193]:
s.index('e')

4

In [198]:
### Retrieve the 7

s= 'Questa e` una stringa 7 che contiene anche un numero'

In [199]:
# '7' is at position 22
s.index('7')

22

In [200]:
s2= s.split(' ')

type(s2[4])

str

In [201]:
s2

['Questa',
 'e`',
 'una',
 'stringa',
 '7',
 'che',
 'contiene',
 'anche',
 'un',
 'numero']

In [204]:
x= int(s2[4])
x

7

In [206]:
s.count('a')

4

In [207]:
s.find('a') # first index position he finds

5

In [210]:
## create a list out of it
s.split(sep= ' ')  # separate by a space

['Questa',
 'e`',
 'una',
 'stringa',
 '7',
 'che',
 'contiene',
 'anche',
 'un',
 'numero']

In [211]:
s

'Questa e` una stringa 7 che contiene anche un numero'

In [212]:
s.split(sep= 'a')  ## separate at any element specified

['Quest', ' e` un', ' string', ' 7 che contiene ', 'nche un numero']

### <font color ='green' > Main Data Structures

* Lists
* Arrays and Matrices
* Dictionaries

    
- Not necessarly used:
    * Tuples 
    * Sets

#### Lists

In [342]:
l = ['a','b','c']
l

['a', 'b', 'c']

In [343]:
type(l)

list

In [344]:
l[2]

'c'

In [345]:
l

['a', 'b', 'c']

In [346]:
## Here the list gets modified because append is a method!
l.append('d')
# l

In [347]:
l

['a', 'b', 'c', 'd']

In [348]:
l + ['e']

['a', 'b', 'c', 'd', 'e']

In [349]:
l

['a', 'b', 'c', 'd']

In [350]:
# summing up two lists
l= l + [3]
l

['a', 'b', 'c', 'd', 3]

In [351]:
# Do not forget variable assignment, list has not been updated here
l

['a', 'b', 'c', 'd', 3]

In [352]:
l.remove('b')
l

['a', 'c', 'd', 3]

In [353]:
# Tale 2nd and 3rd element
l[1: 3 ]

['c', 'd']

In [354]:
print(l[-1]) # take last element
print() #empty row

print(l[1:3])
print() 


### print list in revers order
print(l[::-1])

3

['c', 'd']

[3, 'd', 'c', 'a']


In [355]:
l

['a', 'c', 'd', 3]

In [356]:
l[0:2]

['a', 'c']

In [357]:
l[:-1]

['a', 'c', 'd']

In [358]:
# take everything
l[:]

['a', 'c', 'd', 3]

In [361]:
## change a value of list by using indexing

l[0] = 5   #value in position 0 is set to 5
l

[5, 'c', 'd', 3]

###### Exercise Slicing
Select the internal list

In [237]:
nested = [1,2,3,[4,5,['seleziona questa stringa']]]


4

In [263]:
nested[-1][-1][0]

# nested[3][2][0]

'seleziona questa stringa'

#### Arrays  and Matrices
- use Numpy libraries

In [265]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [264]:
matrix = np.arange(1,10)

print(matrix)

[1 2 3 4 5 6 7 8 9]


In [266]:
type(matrix)

numpy.ndarray

###### Exercise
Use print() command and print formatting to return the number of elements like below

In [267]:
print(f'La matrice ha {len(matrix)} elementi')

La matrice ha 9 elementi


In [268]:
## reshaping matrix

matrix= matrix.reshape(3,3)
print(matrix)

print(f'\n Adesso la matrice ha {len(matrix)} elementi, ognuno è una lista di 3 numeri')

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 Adesso la matrice ha 3 elementi, ognuno è una lista di 3 numeri


###### Exercise
Use slicing to return only [5, 6]

In [270]:
matrix[1][1:]

array([5, 6])

In [272]:
#Use slicing to return only [4, 6]

matrix[1][[0,2]]

array([4, 6])

Getting min, max, mean, std

In [273]:
print('Min is ', matrix.min())
print('Max is ', matrix.max())
print('Mean is ', matrix.mean())
print('Std Dev is ', matrix.std())

Min is  1
Max is  9
Mean is  5.0
Std Dev is  2.581988897471611


In [274]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [275]:
# total sum
np.sum(matrix)

45

In [276]:
# sum by column
np.sum(matrix, axis=0)

array([12, 15, 18])

In [277]:
# sum by row
np.sum(matrix, axis=1)

array([ 6, 15, 24])

In [280]:
# Getting array of numbers equally separated

np.linspace(start=0, stop=20, num=5)

array([ 0.,  5., 10., 15., 20.])

In [291]:
## Getting a random number given an interval

np.random.seed(1)
np.random.randint(1,100, 1)

array([38])

#### Dictionaries
- structure of key: value

In [307]:
diz = {'federico': 3, 'johnny': 5, 'jessica': 7, 'laura': 2}

# To pick Johnny, cannot do diz[1], like in the lists, but:

diz['federico']

3

In [308]:
type(diz)

dict

In [309]:
try:
    diz[2]
except:
    #raise ValueError('I cannot use indexing for dictionaries; I must select a key')
    print('I cannot use indexing for dictionaries; I must select a key')

I cannot use indexing for dictionaries; I must select a key


In [310]:
## Adding new key to dictionary

diz['francesco'] = 11
diz

{'federico': 3, 'johnny': 5, 'jessica': 7, 'laura': 2, 'francesco': 11}

In [312]:
diz

{'federico': 3, 'johnny': 12, 'jessica': 7, 'laura': 2, 'francesco': 11}

In [306]:
## Modifying existing key in the dictionary

diz['johnny']= diz['johnny'] + 7
# diz['johnny'] += 7   # same way to do it
diz

{'federico': 3, 'johnny': 12, 'jessica': 7, 'laura': 2, 'francesco': 11}

In [313]:
# get only keys from the dictionary

diz.keys()

dict_keys(['federico', 'johnny', 'jessica', 'laura', 'francesco'])

In [314]:
# get only the values from the dictionary

diz.values()

dict_values([3, 12, 7, 2, 11])

In [316]:
#Exercise Slicing lists with dictionary
## Take 2nd and 3rd letter of 'stringa3'

l= [['Stringa1' , ['stringa2', 18, {'johnny': ['stringa3']} ]]]

In [322]:
l[0][-1][-1]['johnny'][0]

'stringa3'

#### Sets

In [323]:
### Takes only unique values and also sorted

l= [1,2,1,3,4,4]

s = set(l)
s

{1, 2, 3, 4}

In [324]:
type(s)

set

In [325]:
s2 = set([0,2,3,5,7])
s2

{0, 2, 3, 5, 7}

In [326]:
## Intersection - takes only common elements

s.intersection(s2)

{2, 3}

In [331]:
## Union - takes all elements

s3 = s.union(s2)
s3

{0, 1, 2, 3, 4, 5, 7}

In [333]:
s

{1, 2, 3, 4}

In [334]:
s.remove(2)
s

{1, 3, 4}

#### Tuples

In [336]:
1+2, 3+5

(3, 8)

In [337]:
t= (1,2,3)

type(t)

tuple

In [340]:
t[0] = 5

TypeError: 'tuple' object does not support item assignment

In [339]:
l= [1,2,3]
l[0] = 5

l

[5, 2, 3]

In [ ]:
t.count(1)

In [341]:
t= t + (4,7)
t

(1, 2, 3, 4, 7)

#### <font color='green'> Comparison Operators

In [362]:
2>1

True

In [363]:
2>=1

True

In [364]:
## Comparison is with ==
## just = is used for variable assignment

x=3

2==1

False

In [365]:
1==1

True

In [366]:
1 in [1,2,3]

True

In [367]:
1 in [2,3]

False

In [368]:
1 not in [2,3]

True

In [369]:
not 1 not in [2,3]

False

In [372]:
not not 1 not in [2,3]

True

### <font color = 'green'> Special Characters and Built-in functions
    
- True, False

- max, min, 
- any, all
- round
- print
- type
- input

In [373]:
type(True)

bool

In [375]:
# at least one True, and it returns True
any([1==1, 1==0, 5<2])

True

In [376]:
# Needs all to be True, to return True

all([1==1, 2==2, 3==3, 1==0])

False

In [377]:
all([1==1, 3>0])

True

In [378]:
round(3.77777)

4

In [379]:
round(3.77777 , 2)

3.78

In [380]:
## Using Input to assign interactively

num = int(input('Inserisci un numero  '))

Inserisci un numero  12


In [381]:
num

12

###  <font color='green'> Logical operators and Conditional Statements - if, elif, else, AND, OR

In [382]:
matrix = np.arange(1,10).reshape(3,3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [383]:
len(matrix)

3

In [385]:
# matrix.shape

In [386]:
# Single if
if len(matrix) == 3:
    print('matrix has 3 elements')

matrix has 3 elements


In [388]:
## Example if else - have to be mutually exclusive

if len(matrix) == 5:
    print('Risposta giusta')
else:
    print('Risposta sbagliata')

Risposta sbagliata


In [389]:
## Example if, elif, else - have to be mutually exclusive

lista= [1,2,3,4,5,6,7,8,9]

if len(lista)<=3:
    print('lista corta')
    
elif len(lista)>3 and len(lista) <=6:
    print('lista media')
    
else:  # if len > 6
    print('lista lunga')

lista lunga


In [390]:
# If I use elif without making mutually exclusive conditions,
## it only runs the first true condition

lista= [1,2,3,4,5,6,7,8,9]

if len(lista)<=3:
    print('lista corta')
    
elif len(lista)>=2:
    print('lista media')
    
elif len(lista)>=7:
    print('lista lunga')

lista media


In [391]:
## With if it runs any true condition

lista= [1,2,3,4,5,6,7,8,9]

if len(lista)<=3:
    print('lista corta')
    
if len(lista)>=2:
    print('lista media')
    
if len(lista)>=7:
    print('lista lunga')

lista media
lista lunga


##### AND/OR operators

In [392]:
l = np.arange(10)
l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [393]:
s= 'Hello'

In [394]:
## And operator - both valids

if len(l) >=3 and len(s)>= 100:
    print('Both conditions are valid')
else:
    print('Some is not valid')

Some is not valid


In [395]:
## Or operator - at least one valid

if len(l) >=3 or len(s)>= 100:
    print('At least one is valid')
else:
    print('None of them is valid')

At least one is valid


In [396]:
if 3>2:
    print('La prima condizione che ho scritto è vera')
    if 3<2:
        print('La seconda condizione è vera')
    else:
        print('la seconda condizione è falsa')
else:
    print('La prima è falsa falsa')

La prima condizione che ho scritto è vera
la seconda condizione è falsa


###### Exercise
Take a number in input, and print "Number is even" if it is divisible by 2, else "Number is odd"

In [399]:
n = 21

if n%2 ==0:
    print('it is even')
else:
    print('it is odd')

it is odd


#### <font color = 'green'> Handling Errors with Try-Except clause

In [401]:
# Now num is not defined
try:
    print(nuova_variabile)
except:
    print('The variable does not exist')

The variable does not exist


In [404]:
try:
    2/0
except:
    print('It was not possible to execute the try clause')

It was not possible to execute the try clause


In [410]:
## Other way
try:
    2/0
except:
    pass

Question: what is the only error immune to the try except, that is it would appear for sure also with this statement?


Answer: Syntax/Indentation error

## <font color='green'> For Loops

In [43]:
l= list(np.arange(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### Iterator - based for loop

###### SYNTAX

In [48]:
## Example: Multiply each elemnt of the list by 3 using for loop

### SYNTAX ITERATOR-BASED FOR LOOP

for elem in l:
    print(elem*3)

0
3
6
9
12
15
18
21
24
27


In [49]:
#### print each word in the sentence using for loop

s= "I would like to eat a very good meal tonight"

s[1]

' '

In [51]:
## Transforming string of letters into list of words

words = s.split(' ')
words

['I', 'would', 'like', 'to', 'eat', 'a', 'very', 'good', 'meal', 'tonight']

In [55]:
for word in words:
    print(word)

I
would
like
to
eat
a
very
good
meal
tonight


In [56]:
diz = {'federico': 3, 
       'johnny': 5, 
       'jessica': 7, 
       'laura': 2,
       'francesco': 11}

diz

{'federico': 3, 'johnny': 5, 'jessica': 7, 'laura': 2, 'francesco': 11}

In [57]:
len(diz)

5

In [40]:
## Print each name of the dictionary

print(list(diz.keys())[0])
print(list(diz.keys())[1])
print(list(diz.keys())[2])
print(list(diz.keys())[3])
print(list(diz.keys())[4])

federico
johnny
jessica
laura
francesco


In [64]:
## Print each name of the dictionary using a for loop

for name in diz.keys():
    print(name)

federico
johnny
jessica
laura
francesco


In [65]:
l= ['a', 'b', 'c', 5, 'd']

for elem in l:
    print(elem)

a
b
c
5
d


<b> Exercise: write for loop which prints N times the name of each key.

In [66]:
diz

{'federico': 3, 'johnny': 5, 'jessica': 7, 'laura': 2, 'francesco': 11}

In [68]:
n = 3

for name in diz:
    print( (name + ' ') * n)

federico federico federico 
johnny johnny johnny 
jessica jessica jessica 
laura laura laura 
francesco francesco francesco 


In [ ]:
# Same exercise, but rather than printing, create a new dictionary
# where each new key is the old key* n times, and each value is x**2

# Example output:
# {'federico federico federico': 9 .....}

In [71]:
new_diz = {}

for name in diz:
    
#     print(new_diz.keys())
    
    new_diz[(name + ' ')*n] = diz[name]**2
    
#     print()
    
new_diz

{'federico federico federico ': 9,
 'johnny johnny johnny ': 25,
 'jessica jessica jessica ': 49,
 'laura laura laura ': 4,
 'francesco francesco francesco ': 121}

<b> NOTE: it does not matter the name, we can call it nome, key, variable etc

In [73]:
## Print each name and value of the dictionary

for key in diz:
    print(key , diz[key])

federico 3
johnny 5
jessica 7
laura 2
francesco 11


<b> Print each name and value of the dictionary ONLY if name starts with 'f' and ends with 'o'

In [74]:
s= 'Hello'

In [75]:
s.startswith('H')

True

In [76]:
s.startswith('p')

False

In [77]:
s.endswith('o')

True

In [78]:
for name in diz:
    if name.startswith('f') and name.endswith('o'):
        print(name , diz[name])

federico 3
francesco 11


<b> Print each name and value of the dictionary ONLY if name starts with 'l' or 'j' 

In [80]:
for name in diz:
    if name.startswith('l') or name.startswith('j'):
        print(name , diz[name])

johnny 5
jessica 7
laura 2


### Traditional for loop using range( )
- always valid - more powerful way to do it

In [81]:
matrix = np.arange(1,10).reshape(3,3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
### Exercise: print each row of matrix using iterator-based for loop

len(matrix)

3

In [83]:
for elem in matrix:
    print(elem)

[1 2 3]
[4 5 6]
[7 8 9]


###### SYNTAX

In [85]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [91]:
## Same with traditional foor loop using range()

for i in range(0, len(matrix)):
#     print(i)
    print(matrix[i])
    print()


[1 2 3]

[4 5 6]

[7 8 9]



In [90]:
for i in range(1, len(matrix)):
#     print(i)
    print(matrix[i])
    print()


[4 5 6]

[7 8 9]



In [93]:
### Given a matrix, return a new matrix where you print with the reverse order

for i in range(0, len(matrix)):
    
    print(matrix[len(matrix) -1 - i])

[7 8 9]
[4 5 6]
[1 2 3]


In [96]:
matrix[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [95]:
# Alternative with previous kind of loop

for elem in matrix[::-1]:
    print(elem)


[7 8 9]
[4 5 6]
[1 2 3]


<b> Exercise: create a new list (of numbers) where you subtract each elem with the one after. If there is no any elem after, take the same elem of the original list

In [97]:
l= [5,8,3,6,2]

# output [-3, 5, -3, 4, 2]
new_l= []


for i in range(len(l)):
    
    if i == len(l) -1:
        new_l.append(l[i])
        
    else:
        new_l.append(l[i] - l[i+1])

In [98]:
new_l

[-3, 5, -3, 4, 2]

<b> Exercise: Return a new list in which each number is summed by two numbers after; If there are no numbers after, leave the number as it is.

In [27]:
lista= [1,2,3,4,5,6,7,8,9]

In [101]:
new_l = []

for i in range(len(lista)):
    
    if i <= len(lista) -1 -2:
        new_l.append(lista[i] + lista[i+2])
        
    else:
        new_l.append(lista[i])
        
new_l   

[4, 6, 8, 10, 12, 14, 16, 8, 9]

In [103]:
### Let's try it again with try except - less elegant solution, I am not having full control!

new_l = []

for i in range(len(lista)):
    
    try:
        new_l.append(lista[i] + lista[i+2])
        
    except:
        new_l.append(lista[i])
        
new_l   

[4, 6, 8, 10, 12, 14, 16, 8, 9]

#### List Comprehension
- 3rd kind of iteration

In [104]:
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [117]:
## Suppose I want to mupltiply by 10 each element of a list, I can do simply

[elem*10 for elem in lista]

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [118]:
np.array(lista)*10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

##### Exercise
Write the same of the list comprehension using traditional for loops

In [108]:
# recall
['a']  + ['b']

['a', 'b']

In [109]:
## Iterator Based for loop

new_l = []

for elem in lista:
    new_l.append(elem*10)
        
new_l

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [110]:
## For loop using range()

new_l = []

for i in range(0, len(lista)):
    new_l.append(lista[i]*10)
    
new_l

[10, 20, 30, 40, 50, 60, 70, 80, 90]

#### Using Break in a for loop 
- it requires using logical operators

In [111]:
## Example: Write for loop to print numbers from 1 to 10 and use 'break' to actually print only numbers from 1 to 7

for i in range(10):
    if i<= 7:
        print(i)
        
    else:
        break  ## Interrupt loop

0
1
2
3
4
5
6
7


#### Using Continue in a for loop 
- it requires using logical operators

In [112]:
## Example: Write for loop to print numbers from 1 to 10 and use 'continue' to skip the number 6 and 8


for i in range(10):
    if i==6 or i==8:
        continue
    else:
        print(i)

0
1
2
3
4
5
7
9


In [113]:
for i in range(10):
    if i not in [6,8]:
        print(i)

0
1
2
3
4
5
7
9


### Exercises for loops

In [153]:
### Use for loop to create a list having 2 elems which are those in 1st and 5th position of a string 

s= 'stringa3'

In [154]:
for i in range(len(s)):
    print(s[i])

s
t
r
i
n
g
a
3


In [155]:
list_idx = []

for i in range(len(s)):
    if i in [0, 4]:
        list_idx.append(s[i])

        
list_idx

['s', 'n']

In [159]:
## Extract word2 and return a string which has the 2nd and 5th elem of it

l= [1, 2, {'word1': [['word2']]}]

old_s = l[-1]['word1'][0][0]
old_s

'word2'

In [161]:
new_s = ''

for i in range(len(s)):
    if i in [1, 4]:
#         new_s = new_s + s[i]
        new_s += s[i]


new_s

'tn'

##### Programma che legge una lista di numeri e crea un dizionario dove ogni numero diventa chiave (in formato stringa), e lo stesso numero alla seconda il valore 

In [164]:
l= np.random.randint(0, 9, size= 10 )
l

array([3, 0, 1, 7, 1, 3, 4, 1, 6, 1])

In [166]:
new_diz = {}

for elem in l:
    new_diz[str(elem)] = elem **2
    
new_diz

{'3': 9, '0': 0, '1': 1, '7': 49, '4': 16, '6': 36}

In [ ]:
### Same exercise with using range() in the loop

In [167]:
new_diz = {}

for i in range(0, len(l)):
    new_diz[ str(l[i])] = l[i]**2
    
new_diz

{'3': 9, '0': 0, '1': 1, '7': 49, '4': 16, '6': 36}

In [168]:
### Same exercise, but the key is the next number in the list (if there is no, use the same number)

new_diz = {}


for i in range(0,len(l)):
    
    if i<= len(l) - 1 -1:
        new_diz[str(l[i+1])] = l[i] **2
        
    else:
        new_diz[str(l[i])] = l[i] **2
        
    
new_diz

{'0': 9, '1': 1, '7': 1, '3': 1, '4': 9, '6': 1}

##### Programma che legge una stringa e stampa il numero di 'a' (quante volte il carattere a minuscolo compare in questa stringa

In [169]:
s= 'This is a trial string, just for explanation purposes'

In [170]:
# Using for loop

count = 0

for letter in s:
    if letter =='a':
        count += 1
        
count

4

##### Programma che legge una stringa s e stampa tutti  i caratteri che appaiono dopo una 'a'

In [171]:
for i in range(len(s)):
    if s[i] == 'a':
        print(s[i+1])

 
l
n
t


##### Programma python che inserito un numero n intero stampa tutti i numeri da 0 a n che hanno la cifra finale 3

In [172]:
n = 42

for i in range(n):
    if i%10 == 3:
        print(i)

3
13
23
33


##### Programma che visualizza i numeri da 0 a n in cui la PENULTIMA cifra sia dispari

In [175]:
n= 31


for i in range(n):
    if i>=10 and (i//10)%2 != 0:  
        print(i)

10
11
12
13
14
15
16
17
18
19
30


##### Programma che legge un numero intero n e stampa tutti i numeri da 0 ad n che sono divisibili per 7 e finiscono per 3

In [177]:
n = 300


for i in range(n):
    if i%10 == 3 and i%7==0:
        print(i)

63
133
203
273


##### Calculate the sum of all numbers from 1 to a given number

In [178]:
n = 5

somma = 0

for i in range(0, n+1):
    somma +=1


somma  

6

##### Write a program to print the next 10 multiples of a given number

In [181]:
n= 5

for i in range(1,10):
    print(n * (i+1))

10
15
20
25
30
35
40
45
50


##### Print list in reverse order using a loop

In [187]:
l = [10, 20, 30, 40, 50]
# reverse list

l2 = []


for i in range(len(l)):
    l2.append( l[len(l) - 1 -i ])

l2

[50, 40, 30, 20, 10]

##### Display numbers from -10 to -1 using for loop

In [189]:
for i in range(1,11):
    print(i-11)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


In [190]:
for i in range(-10,0):
    print(i)

-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


##### Use a loop to display elements from a given list present at odd index positions

In [191]:
my_list = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
new_list = []


for i in range(0, len(my_list)):
    if i%2 !=0:
        new_list.append(my_list[i])
        
        
new_list

[20, 40, 60, 80, 100]

#### Calculate the cube of all numbers from 1 to a given number

In [192]:
n = 21


for i in range(1, n+1):
    print(i ** 3)

1
8
27
64
125
216
343
512
729
1000
1331
1728
2197
2744
3375
4096
4913
5832
6859
8000
9261


##### Find maximum in a list without using max()

In [193]:
l = [3, 0, 11, 4, 6]

In [194]:
max(l)

11

In [195]:
max_num = l[0]

for elem in l:
    
    if elem > max_num:
        max_num = elem

        
max_num

11

### <font color='green'> While Loops

Print each number of <b> lista </b> and until you find one which is divisible by 7

In [196]:
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [197]:
index= 0

while lista[index] %7 != 0:    ## as long as condition is True, continue. 
    
    print(lista[index])
    
    index+=1

1
2
3
4
5
6


In [198]:
## Doing the same using for loop (in some cases it is possible, not always!)

for i in range(0, len(lista)):
    
    if lista[i]%7 !=0:
        print(lista[i])
        
    else:
        break

1
2
3
4
5
6


In [ ]:
# Careful, while Loop can be infinite. An example is below (don't run this)

# while 3>0:
#     print('Non finira mai')

#### Exercises While Loops

In [ ]:
# Es: Print First 10 natural numbers using while loop

In [199]:
i = 1
while i <= 10:
    print(i)
    i += 1

1
2
3
4
5
6
7
8
9
10


In [139]:
## Count the total number of digits in a number

In [200]:
num = 75869
count = 0
while num != 0:
    # floor division
    # to reduce the last digit from number
    num = num // 10

    # increment counter by 1
    count = count + 1
print("Total digits are:", count)

Total digits are: 5


In [203]:
## same with for loop

num = 75869
count = 0


for i in range(len(str(num))):
    num = num // 10
    # increment counter by 1
    count = count + 1
    
    if num ==0:
        break
        
print("Total digits are:", count)

Total digits are: 5


## <font color='green'> Defining Functions
- Custom Functions
- Functions VS Class Methods 
- Built-in Functions (max, min, round etc)

Function which takes a list and returns a list having the string version of each element

In [235]:
def convert_elems(lista):
    new = []
    
    for elem in lista:
        new.append(str(elem))
        
    return new

In [236]:
trial = [1,2,3]

convert_elems(trial)

['1', '2', '3']

In [237]:
l2 = [1, 'b', 5, 7, 'z']

convert_elems(l2)

['1', 'b', '5', '7', 'z']

#####  lambda expressions
another way is with lambda function, it's just much shorter but does the same thing

In [238]:
trial = [1,2,3]

list(map(lambda x: str(x), trial))

['1', '2', '3']

Write a function which takes in input a dictionary and returns a new one where each value is multiplied by a factor

In [242]:
def multiply_diz(diz, multiplier):
    new_diz = diz.copy()
    
    for key in diz:
        new_diz[key] = new_diz[key]*multiplier
    
    return new_diz

In [243]:
diz

{'federico': 48, 'johnny': 80, 'jessica': 112, 'laura': 32, 'francesco': 176}

In [247]:
multiply_diz(diz, 2)

{'federico': 96, 'johnny': 160, 'jessica': 224, 'laura': 64, 'francesco': 352}

In [248]:
multiply_diz(diz= diz, multiplier= 2)

{'federico': 96, 'johnny': 160, 'jessica': 224, 'laura': 64, 'francesco': 352}

##### Optional parameters in functions

In [249]:
### Create a function to make the same exercise

#Return a new list in which each number is summed by N numbers after; If there are no N numbers after, leave the number as it is.

def sum_n_after(my_list, n_after=2):
    
    """ Function which takes a list and returns the same list with.... 
    
    my_list: type(list)"""
                  
    new= []
    
    for i in range(len(my_list)):
        if i < len(my_list) - n_after:
            new.append(my_list[i] + my_list[i + n_after])
            
        else: ## when I do not have n_after indexes after, I append the same value of list
            new.append(my_list[i])
                  
    return new

In [250]:
lista = list(np.arange(1, 10))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [255]:
sum_n_after(my_list= lista, n_after=2)

[4, 6, 8, 10, 12, 14, 16, 8, 9]

In [256]:
sum_n_after(lista, n_after=3)

[5, 7, 9, 11, 13, 15, 7, 8, 9]

#### Exercises Functions

In [210]:
### Create a function to make the same exercise

#Return a new list in which each number is summed by two numbers after; If there are no numbers after, leave the number as it is.

def sum_two_after(my_list):
    
    """ Function which takes a list and returns the same list with.... 
    
    my_list: type(list)"""
                  
    ## code here

In [211]:
sum_two_after(my_list = lista)

[4, 6, 8, 10, 12, 14, 16, 8, 9]

In [212]:
sum_two_after(lista)

[4, 6, 8, 10, 12, 14, 16, 8, 9]

In [213]:
l2= [7,13, 260]

sum_two_after(l2)

[267, 13, 260]

In [257]:
#ESERCIZIO

# Voglio scrivere una funzione che mi restituisca la mediana di una lista
# Questa funzione dovrà ricevere delle informazioni in input (di tipo lista) e restituire un risultato di tipo intero in output

# Quando creiamo una funzione, tieniamo sempre bene a mente i parametri che desideriamo avere
# in input e in output!

In [263]:
l= [1,2,3,4,5,6,7,8,9]

l2= [2,1,5,7,6,4,9,8,3]

In [262]:
sorted_list = sorted(l2)
median = sorted_list[len(sorted_list)//2]
median

6

In [264]:
def find_median(lista):
    
    sorted_list = sorted(lista)
    median = sorted_list[len(sorted_list)//2]
    
    return median


In [265]:
find_median(l)

5

In [266]:
find_median(l2)

5

In [ ]:
# Scrivere una funzione python che dato una dizionario contenente le coppie studente/mediavoti
# restituisce una lista contenente i nomi degli studenti ordinati per media.

diz = {'john':30,'paul':18,'george':28,'richard':23}

# con questo dizionario, la funzione dovrà restituirmi: ['paul','richard','george', 'john' ]

In [267]:
sorted(diz.values())

[32, 48, 80, 112, 176]

In [269]:
diz

{'federico': 48, 'johnny': 80, 'jessica': 112, 'laura': 32, 'francesco': 176}

In [268]:
l = []

ordered_votes = sorted(diz.values())

for vote in ordered_votes:
    for name in diz:
        if vote == diz[name]:
            l.append(name)
            
            
l

['laura', 'federico', 'johnny', 'jessica', 'francesco']

In [270]:
def order_students(dictionary):
    
    l = []

    ordered_votes = sorted(dictionary.values())

    for vote in ordered_votes:
        for name in dictionary:
            if vote == dictionary[name]:
                l.append(name)
                
    return l


In [271]:
order_students(diz)

['laura', 'federico', 'johnny', 'jessica', 'francesco']

In [272]:
order_students(dictionary= diz)

['laura', 'federico', 'johnny', 'jessica', 'francesco']

###  <font color='green'> Recap Exercises

In [ ]:
# Implementa il gioco Carta Forbici e Sasso prendendo in input un 
## numero di vittorie massime a cui bisogna arrivare

In [ ]:
### Code Here

<b> Do the same using while loop

In [ ]:
### Code Here

In [ ]:
## Take maximum sums among all the combinations of two numbers of the two lists

# max( 5+3, 5+0, 5+ 11....... 2+3, 2+0, 2+11.....)

In [ ]:
max(l1) + max(l2)

In [ ]:
l1= [5,2,8,7]
l2 = [3,0, 11, 4, 6]

### Code Here - Sol 1

In [ ]:
### Code Here - Sol 2

In [ ]:
# Print the following pattern:

# 1 
# 1 2 
# 1 2 3 
# 1 2 3 4 
# 1 2 3 4 5

In [132]:
### Code Here


1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [ ]:
## Print the following pattern
# 5 4 3 2 1 
# 4 3 2 1 
# 3 2 1 
# 2 1 
# 1

In [131]:
### Code Here

5 4 3 2 1 
4 3 2 1 
3 2 1 
2 1 
1 
